<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>
<body>
<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$base_url=$storeManager->getStore()->getBaseUrl();
$storename=$storeManager->getStore()->getName();
?>
   <div class="kg-magento-section">
       <div class="headding-section">
       <?php //echo $this->getLayout()->createBlock("Magento\Theme\Block\Html\Header\Logo")->setTemplate("Magento_Theme::html/header/logo.phtml")->toHtml(); ?>
       <?php 
	    $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();		
		$logo = $objectManager->get('\Magento\Theme\Block\Html\Header\Logo');
	   ?>
          <a href="#"><img src="<?php echo $logo->getLogoSrc()?>" alt=""></a>
       </div>
         <div class="kg_error_section" style="display:none">
	     </div>
       <div class="kg-magnto-content">
           <div class="content-block">
                <h2><b><?php echo $storename; ?></b></h2>
                <p class="description">This store is password protected. Use the password to enter the store.</p>
           </div>

           <div class="content-block">
        
            <form action="<?php echo $base_url;?>passwordprotector/index/password"  method="post">
            <input type="hidden" name="authenticity_token">
                <div class="form-section">
                  <div class="form-wrapper">
                    <div class="label-wrapper">
                      <label for="password">Enter store password</label>
                    </div>
                    <input type="password" class="form-input " id="password" name="password" autocomplete="nope">
                    <div class="error-container" style="display:none">
                    	This Field Requird.
                    </div>
                  </div>
                </div>
                <button type="submit" id="submit">Enter</button>
    </form>
          </div>
          <!--<div class="content--block">
            <div class="content--desc">
              <span>
                Are you the store owner?
                <a href="/admin">
                  Log in here
                </a>
              </span>
            </div>
          </div>-->
           
       </div>
   </div>
</body>
</html>
<script>
$(document).ready(function()
{
  $('#submit').click(function()
  {
	 jQuery('.kg_error_section').hide();
	 if($('#password').val() == '')
     {
	 	$('.error-container').show();
	 }else
	 {
		 $('.error-container').hide();
	 }
	 $.ajax({
        type: "post",
        url: "<?php echo $base_url;?>passwordprotector/index/password",
        data: {password:$('#password').val()},
        success: function (response) {
            if(response === "success") {
			 location.reload();
            } else{
				jQuery('.kg_error_section').show();
               jQuery('.kg_error_section').html(response);
            }
        }
    });
    return false;
  });
});
</script>

<style>
 body{
        font-family: ShopifySans, -apple-system, BlinkMacSystemFont, San Francisco, Segoe UI, Roboto, Helvetica Neue, sans-serif;
        margin: 0;
    }
.error-container {
    color: red;
}
.kg-magento-section {
    box-sizing: border-box;
    max-width: calc(410px + 4rem);
    min-height: calc(100vh - 5rem);
    margin: 0 auto;
    padding: 0 20px;
    padding-top: 107px;
    padding-bottom: 60px;
}
.kg-magento-section .headding-section {
    width: 200px;
    margin-bottom: 70px;
}
.kg-magento-section .content-block {
    margin-bottom: 32px;
    position: relative;
}
.kg-magento-section .content-block h2 {
    font-size: 32px;
    line-height: 30px;
    font-weight: 300;
    margin-bottom: 10px;
    margin-top: 0;
    color: #31373D;
}
.kg-magento-section p.description {
    color: #6c6c6c;
    margin: 0;
   
}
.kg-magento-section .form-section {
    display: flex;
    flex-direction: column;
    flex-wrap: wrap;
    margin: -8px;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
}
.kg-magento-section .form-wrapper {
    box-sizing: border-box;
    margin: 0;
    display: flex;
    flex-direction: column;
    padding: 8px;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
}
.kg-magento-section .form-input{
    outline: none;
    max-height: 52px;
    padding: 16px;
    border-color: #8996a3;
    box-shadow: 0 0 0 0.1rem transparent;
    min-width: 75px;
    height: auto;
    margin: 0;
    border: 1px solid #c4cdd5;
    border-radius: 3px;
    text-transform: initial;
    letter-spacing: initial;
    box-sizing: border-box;
    display: block;
    width: 100%;
    transition: box-shadow 100ms cubic-bezier(0.64, 0, 0.35, 1),border-color 100ms cubic-bezier(0.64, 0, 0.35, 1),-webkit-box-shadow 100ms cubic-bezier(0.64, 0, 0.35, 1);
}
.kg-magento-section button {
    display: inline-block;
    padding: 16px 29px;
    border-radius: 4px;
    font-family: ShopifySans, Helvetica, Arial, sans-serif;
    font-weight: 700;
    font-size: 1em;
    line-height: 1.133;
    -webkit-font-smoothing: antialiased;
    transition: 150ms ease;
    transition-property: background-color, border-color, box-shadow, color;
    text-align: center;
    -webkit-user-select: none;
    user-select: none;
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    cursor: pointer;
    box-shadow: 0 5px 15px 0 rgb(0 0 0 / 15%);
    background-color: #f26322;
    color: #ffffff;
    border-width: 1px;
    border-style: solid;
    border-color: transparent;
    margin: 15px 0;
}
.kg-magento-section .content--desc a {
    color: #479ccf;
}
.kg-magento-section .label-wrapper {
    align-items: baseline;
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    margin: 0 -4px;
}
.kg-magento-section .label-wrapper label {
    font-size: 16px;
    line-height: 24px;
    margin: 0 4px 4px 4px;
}
.kg_error_section {

    color: #721c24;
    background-color: #f8d7da;
    border-color: #f5c6cb;
    position: relative;
    padding: 0.75rem 1.25rem;
    margin-bottom: 1rem;
    border: 1px solid transparent;
    border-radius: 0.25rem;

}
@media screen and (max-width:576px) {
.kg-magento-section .headding-section {
    margin-bottom: 30px;
}
}
</style>